<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AssemblyName>thuytrang.Migrator</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>thuytrang.Migrator</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>
  <ItemGroup>
    <None Update="appsettings.json;log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Abp.Castle.Log4Net" Version="9.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\thuytrang.Core\thuytrang.Core.csproj" />
    <ProjectReference Include="..\thuytrang.EntityFrameworkCore\thuytrang.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\thuytrang.Web.Core\thuytrang.Web.Core.csproj" />
  </ItemGroup>
</Project>